services:
  twilio-verify:
    image: twilio-verify:latest
    build:
      context: .
      args:
        - PORT=${PORT}
    container_name: twilio-verify
    ports:
      - "127.0.0.1:${PORT}:${PORT}"
    env_file:
      - .env
    environment:
      - PORT=${PORT}
    restart: always
    user: "node"
    networks:
      - local_net

networks:
  local_net:
    driver: bridge