### Enviar código de verificación
POST http://localhost:3000/api/send-code
Content-Type: application/json
Authorization: Basic TU_USUARIO:TOKEN
Accept: application/json

{
  "phoneNumber": "+521234567890"
}

###

### Verificar código recibido por SMS
POST http://localhost:3000/api/verify-code
Content-Type: application/json
Authorization: Basic TU_USUARIO:TOKEN
Accept: application/json

{
  "phoneNumber": "+521234567890",
  "code": "123456"
}
