@host = http://localhost:5004
@basicAuth = YWRtaW46c3VwZXJzZWN1cmVwYXNzd29yZA==

### Enviar código de verificación
POST http://localhost:5004/api/verify/send-code
Content-Type: application/json
Authorization: Basic {{basicAuth}}

{
  "phoneNumber": "+527225494079"
}

### Verificar código
POST http://localhost:5004/api/verify/verify-code
Content-Type: application/json
Authorization: Basic {{basicAuth}}

{
  "phoneNumber": "+527225494079",
  "code": "458121"
}
